// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vlmqtzjopiwclrpqxubk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsbXF0empvcGl3Y2xycHF4dWJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NTQyMTYsImV4cCI6MjA2NTAzMDIxNn0.iqTMsOzydRDwfXIsbJzjnzOZ8fB9duNGWH0X9_-JVoU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);